add chart hooks to migration-job template
odpf/charts pull request #36
Opened 2022-01-20 06:31 UTC by bsushmith

2022-01-21 06:46 UTC, AkarshSatija approved these changes

2022-01-21 06:47 UTC, AkarshSatija requested changes

2022-01-21 06:47 UTC, AkarshSatija commented on stable/app/templates/migration-job.yaml
> +      # This is what defines this resource as a hook. Without this line, the
Requires upgrading chart version as well

2022-01-21 06:56 UTC, bsushmith commented on stable/app/templates/migration-job.yaml
> +      # This is what defines this resource as a hook. Without this line, the
Done.

2022-01-21 07:26 UTC, snorlacs commented on stable/app/templates/migration-job.yaml
> +      "helm.sh/hook-delete-policy": hook-succeeded
This means that only if the job completes successfully we are deleting the job. For failed job we have to manually delete the job always

2022-01-21 07:27 UTC, snorlacs commented on stable/app/templates/migration-job.yaml
> +      "helm.sh/hook-delete-policy": hook-succeeded
Can we make hook `pre-install` and delete for both failed and successful jobs

2022-01-28 06:53 UTC, snorlacs approved these changes

2022-01-28 16:24 UTC, AkarshSatija approved these changes

2022-01-28 16:25 UTC, merged